/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 jsf.gltf 
Author: Petri Liuhto (https://sketchfab.com/petri.liuhto)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/jedi-star-fighter-0b641c2f2b854f1f9ae7f2a731e44dbd
Title: Jedi Star Fighter
*/

import { useGLTF, Float } from "@react-three/drei";

export function Jsf(props) {
	const { nodes, materials } = useGLTF("jsf.gltf");
	return (
		<Float
			speed={2.5}
			rotationIntensity={0.3}
			floatIntensity={5}
			floatingRange={[1, 10]}
		>
			<group
				{...props}
				dispose={null}
			>
				<group
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<mesh
						geometry={nodes.main_jsf_mainMat_0.geometry}
						material={materials.jsf_mainMat}
					/>
					<mesh
						geometry={nodes.main_jsf_mainMat_0_1.geometry}
						material={materials.jsf_mainMat}
					/>
				</group>
				<group
					rotation={[-Math.PI / 2, 0, 0]}
					scale={100}
				>
					<mesh
						geometry={nodes.aux_jsf_auxMat_0.geometry}
						material={materials.jsf_auxMat}
					/>
					<mesh
						geometry={nodes.aux_jsf_auxMat_0_1.geometry}
						material={materials.jsf_auxMat}
					/>
				</group>
			</group>
		</Float>
	);
}

useGLTF.preload("jsf.gltf");
export default Jsf;
